config/routes.rb
Twoweektedtalk::Application.routes.draw do
  resources :plans

  get "about" => 'page#about', as: :about
  get "newsletter" => 'page#newsletter', as: :newsletter
  get "newsletter" => 'page#newsletter', as: :subscribe
  get "recent" => 'page#recent', as: :recent
  root 'page#home'

end

app/models/plan.rb
class Plan < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  def home
    @plan = Plan.new
    @placeholder = Plan.last
    @plans = Plan.all
  end

  def recent
     @plans = Plan.all.reverse
  end

  def about
  end

  def contact
  end

  def newsletter
  end
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        redirect_to recent_path
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        redirect_to recent_path
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title, :actionsteps, :reason, :twitter)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
    @placeholder = Plan.last
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

      if @plan.save
        redirect_to recent_path
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        redirect_to recent_path
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title, :actionsteps, :reason, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title)
      base_title = "Two Week TED Talk"
      if page_title.empty?
        base_title +" | What will you create?"
      else
        "#{base_title} | #{page_title}"
      end
    end

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>


  <body>
    <%= render 'shared/topbar' %>
    <div class="row">


      <h5 class="notice"><%= notice %></h5>
      <h5 class="alert"><%= alert %></h5>

      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47082907-1', 'twoweektedtalk.com');
    ga('send', 'pageview');

  </script>
  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/all.html.erb
<div class="recent">

<h1>Recently posted <a href="https://twitter.com/search?q=%23twoweektedtalk&src=hash">#twoweektedtalk</a></h1>

    <% @plans.each do |plan| %>
    <div class="panel" style="">

      <h2 style="padding:  0.5em 1em 0.3em;"><%= plan.title %></h2>
      <p class="text-right column">
        <strong>Posted by @<a href="http://twitter.com/<%= plan.twitter %>"><%= plan.twitter %></a>
    <%= distance_of_time_in_words(plan.created_at, Time.now) %> ago</strong>
      </p>
      <dl class="accordion" data-accordion>
        <dd>
          <a href="#panel<%= plan.id %>-1">How</a>
          <div id="panel<%= plan.id %>-1" class="content">
            <%= plan.actionsteps %>
          </div>
        </dd>
        <dd>
          <a href="#panel<%= plan.id %>-2">Why</a>
          <div id="panel<%= plan.id %>-2" class="content">
            <%= plan.reason %>
          </div>
        </dd>
      </dl>
</div>
<br>
<hr>


  <% end %>
</div>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<div class="text-">

<h1 class="text-center">
<%= image_tag 'twtt.png' %>
</h1>

<h2 title="Description">Challenge yourself to do something "<a href="http://ted.com"><strong>TED worthy</strong></a>" in two weeks.</h2>

<h3>Post a goal below and accomplish it in two weeks</h3>
<p>This is an opportunity for you to challenge something that you've been putting off. This is your chance to finally do that "thing" you've been thinking of. You can pick anything. Its completely up to you.</p>
<p>Anyone can post on the TWTT wall. By posting, you are sharing your idea with the world. You are making a commitment to make progress on your goal. At the end of two weeks, please come back and report how you succeeded/redetermined.</p>
<br>
<div class="panel callout" style="    border-top: .8em solid rgb(22, 157, 72);" >
  <div style='padding:1em 1.2em;'>
    <%= render 'plans/form' %>
  </div>
</div>
<h3>Join others</h3>
<p>This website lets you simply share your TWTT project. The moment you post your TWTT, you have two weeks. After your two weeks, you will get an email asking you to post a final report.</p>

<%= link_to 'See the other #twoweektedtalks', recent_path, :class=> 'no-butt button tiny' %>

<br><br>
<%= render 'shared/share' %>

</div>

app/views/page/newsletter.html.erb
<%= render 'shared/newsletter' %>

<%= render 'shared/share' %>

<%= link_to 'See other #twoweektedtalks', recent_path, :class=>"button"

app/views/page/recent.html.erb
<div class="recent">

<h1>Recently posted <a href="https://twitter.com/search?q=%23twoweektedtalk&src=hash">#twoweektedtalk</a></h1>

    <% @plans.each do |plan| %>
    <div class="panel" style="">

      <h2 style="padding:  0.5em 1em 0.3em;"><%= plan.title %></h2>
      <p class="text-right column">
        <strong>Posted by @<a href="http://twitter.com/<%= plan.twitter %>"><%= plan.twitter %></a>
        <%= link_to plan do %>
    <%= distance_of_time_in_words(plan.created_at, Time.now) %> ago <% end %></strong>
      </p>
      <dl class="accordion" data-accordion>
        <dd>
          <a href="#panel<%= plan.id %>-1">How</a>
          <div id="panel<%= plan.id %>-1" class="content">
            <%= plan.actionsteps %>
          </div>
        </dd>
        <dd>
          <a href="#panel<%= plan.id %>-2">Why</a>
          <div id="panel<%= plan.id %>-2" class="content">
            <%= plan.reason %>
          </div>
        </dd>
      </dl>
</div>
<br>
<hr>


  <% end %>
</div>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4 class="subheader">What will do you for your #twoweektedtalk?</h4>
    <%= f.text_field :title, :placeholder=> truncate(@placeholder.title, :length => 85), :input_html => {:maxlength => 140} , :required => true %>
  </div>
  <div class="field">
    <h4 class="subheader">How are you doing this?</h4>
    <%= f.text_area :actionsteps, :placeholder=> truncate(@placeholder.actionsteps, :length => 150), :required => true %>
  </div>
  <div class="field">
    <h4 class="subheader">Why is this important?</h4>
    <%= f.text_field :reason, :placeholder=> truncate(@placeholder.reason, :length => 85), :required => true %>
  </div>
  <div class="field">
    <h4 class="subheader">What is your twitter handle? (so we can contact you in two weeks)</h4>
    <%= f.text_field :twitter, :placeholder=>"@twoweektedtalk (without the @-sign)", :required => true %>
  </div>
  <div class="actions">
    <%= f.submit 'Start the countdown', :class=>"button even success large" %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<%= render 'shared/newsletter' %>

<%= link_to 'View recent #twoweektedtalks', recent_path, :class=>'button' %>

app/views/plans/index.html.erb
<%= render 'shared/newsletter' %>

<%= link_to 'View recent #twoweektedtalks', recent_path, :class=>'button secondary' %>

app/views/plans/new.html.erb
<h1>Great!</h1>

<%= render 'shared/newsletter' %>

<%= link_to 'View recent #twoweektedtalks', recent_path, :class=>'button secondary' %>

app/views/plans/show.html.erb
<% provide(:title, @plan.title) %>

<h1>Posted <a href="https://twitter.com/search?q=%23twoweektedtalk&src=hash">#twoweektedtalk</a></h1>

  <div class="panel" style="">

    <h2 style="padding:  0.5em 1em 0.3em;"><%= @plan.title %></h2>
    <p class="text-right column">
      <strong>Posted by @<a href="http://twitter.com/<%= @plan.twitter %>"><%= @plan.twitter %></a>
  <%= distance_of_time_in_words(@plan.created_at, Time.now) %> ago</strong>
    </p>
    <dl class="accordion" data-accordion>
      <dd>
        <a href="#panel<%= @plan.id %>-1">How</a>
        <div id="panel<%= @plan.id %>-1" class="content">
          <%= @plan.actionsteps %>
        </div>
      </dd>
      <dd>
        <a href="#panel<%= @plan.id %>-2">Why</a>
        <div id="panel<%= @plan.id %>-2" class="content">
          <%= @plan.reason %>
        </div>
      </dd>
    </dl>
</div>

<%= render 'shared/newsletter' %>

<%= render 'shared/share' %>

app/views/shared/_newsletter.html.erb
<hr>
<!-- Begin MailChimp Signup Form -->
<style type="text/css">
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="http://atriangle.us3.list-manage.com/subscribe/post?u=3d383a081a1cbf7e765e14c3c&amp;id=a9cb689049" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
  <h1><strong>Get inspirational TWTT sent to your inbox</strong></h1>
  <p class="inof">Get the weekly newsletter summarizing the most unique TWTT.</p>
<div class="mc-field-group">
  <input type="email" value="" name="EMAIL" placeholder="email@domain.com" class="required email" id="mce-EMAIL" style="height: 62px;
max-width: 600px;
font-size: 3em; font-family: Georgia;">
</div>

  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_3d383a081a1cbf7e765e14c3c_a9cb689049" value=""></div>
  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"  class="button" style="font-size: 2em;"></div>
</form>
</div>
<script type="text/javascript">
var fnames = new Array();var ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';
try {
    var jqueryLoaded=jQuery;
    jqueryLoaded=true;
} catch(err) {
    var jqueryLoaded=false;
}
var head= document.getElementsByTagName('head')[0];
if (!jqueryLoaded) {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = '//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js';
    head.appendChild(script);
    if (script.readyState && script.onload!==null){
        script.onreadystatechange= function () {
              if (this.readyState == 'complete') mce_preload_check();
        }
    }
}

var err_style = '';
try{
    err_style = mc_custom_error_style;
} catch(e){
    err_style = '#mc_embed_signup input.mce_inline_error{border-color:#6B0505;} #mc_embed_signup div.mce_inline_error{margin: 0 0 1em 0; padding: 5px 10px; background-color:#6B0505; font-weight: bold; z-index: 1; color:#fff;}';
}
var head= document.getElementsByTagName('head')[0];
var style= document.createElement('style');
style.type= 'text/css';
if (style.styleSheet) {
  style.styleSheet.cssText = err_style;
} else {
  style.appendChild(document.createTextNode(err_style));
}
head.appendChild(style);
setTimeout('mce_preload_check();', 250);

var mce_preload_checks = 0;
function mce_preload_check(){
    if (mce_preload_checks>40) return;
    mce_preload_checks++;
    try {
        var jqueryLoaded=jQuery;
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'http://downloads.mailchimp.com/js/jquery.form-n-validate.js';
    head.appendChild(script);
    try {
        var validatorLoaded=jQuery("#fake-form").validate({});
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    mce_init_form();
}
function mce_init_form(){
    jQuery(document).ready( function($) {
      var options = { errorClass: 'mce_inline_error', errorElement: 'div', onkeyup: function(){}, onfocusout:function(){}, onblur:function(){}  };
      var mce_validator = $("#mc-embedded-subscribe-form").validate(options);
      $("#mc-embedded-subscribe-form").unbind('submit');//remove the validator so we can get into beforeSubmit on the ajaxform, which then calls the validator
      options = { url: 'http://atriangle.us3.list-manage1.com/subscribe/post-json?u=3d383a081a1cbf7e765e14c3c&id=a9cb689049&c=?', type: 'GET', dataType: 'json', contentType: "application/json; charset=utf-8",
                    beforeSubmit: function(){
                        $('#mce_tmp_error_msg').remove();
                        $('.datefield','#mc_embed_signup').each(
                            function(){
                                var txt = 'filled';
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        var bday = false;
                                        if (fields.length == 2){
                                            bday = true;
                                            fields[2] = {'value':1970};//trick birthdays into having years
                                        }
                                      if ( fields[0].value=='MM' && fields[1].value=='DD' && (fields[2].value=='YYYY' || (bday && fields[2].value==1970) ) ){
                                        this.value = '';
                      } else if ( fields[0].value=='' && fields[1].value=='' && (fields[2].value=='' || (bday && fields[2].value==1970) ) ){
                                        this.value = '';
                      } else {
                          if (/\[day\]/.test(fields[0].name)){
                                              this.value = fields[1].value+'/'+fields[0].value+'/'+fields[2].value;
                          } else {
                                              this.value = fields[0].value+'/'+fields[1].value+'/'+fields[2].value;
                                          }
                                      }
                                    });
                            });
                        $('.phonefield-us','#mc_embed_signup').each(
                            function(){
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        if ( fields[0].value.length != 3 || fields[1].value.length!=3 || fields[2].value.length!=4 ){
                                        this.value = '';
                      } else {
                          this.value = 'filled';
                                      }
                                    });
                            });
                        return mce_validator.form();
                    },
                    success: mce_success_cb
                };
      $('#mc-embedded-subscribe-form').ajaxForm(options);


    });
}
function mce_success_cb(resp){
    $('#mce-success-response').hide();
    $('#mce-error-response').hide();
    if (resp.result=="success"){
        $('#mce-'+resp.result+'-response').show();
        $('#mce-'+resp.result+'-response').html(resp.msg);
        $('#mc-embedded-subscribe-form').each(function(){
            this.reset();
      });
    } else {
        var index = -1;
        var msg;
        try {
            var parts = resp.msg.split(' - ',2);
            if (parts[1]==undefined){
                msg = resp.msg;
            } else {
                i = parseInt(parts[0]);
                if (i.toString() == parts[0]){
                    index = parts[0];
                    msg = parts[1];
                } else {
                    index = -1;
                    msg = resp.msg;
                }
            }
        } catch(e){
            index = -1;
            msg = resp.msg;
        }
        try{
            if (index== -1){
                $('#mce-'+resp.result+'-response').show();
                $('#mce-'+resp.result+'-response').html(msg);
            } else {
                err_id = 'mce_tmp_error_msg';
                html = '<div id="'+err_id+'" style="'+err_style+'"> '+msg+'</div>';

                var input_id = '#mc_embed_signup';
                var f = $(input_id);
                if (ftypes[index]=='address'){
                    input_id = '#mce-'+fnames[index]+'-addr1';
                    f = $(input_id).parent().parent().get(0);
                } else if (ftypes[index]=='date'){
                    input_id = '#mce-'+fnames[index]+'-month';
                    f = $(input_id).parent().parent().get(0);
                } else {
                    input_id = '#mce-'+fnames[index];
                    f = $().parent(input_id).get(0);
                }
                if (f){
                    $(f).append(html);
                    $(input_id).focus();
                } else {
                    $('#mce-'+resp.result+'-response').show();
                    $('#mce-'+resp.result+'-response').html(msg);
                }
            }
        } catch(e){
            $('#mce-'+resp.result+'-response').show();
            $('#mce-'+resp.result+'-response').html(msg);
        }
    }
}

</script>
<!--End mc_embed_signup-->

app/views/shared/_share.html.erb
<p>
<hr style="padding-bottom: 0em;">
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twoweektedtalk" data-size="large" data-hashtags="twoweektedtalk">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</p>

app/views/shared/_topbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'TWTT', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li>
        <%= link_to "Recent", recent_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <a href="http://twitter.com/twoweektedtalk">Contact</a>
      </li>
      <li class="active">
        <%= link_to "Subscribe", newsletter_path %>
      </li>


    </ul>

    <!-- Left Nav Section -->

  </section>
</nav>